INSERT INTO comentario (comentario, usuario_id) VALUES('que faça concurso e a administração faça uma reciclagem com seus agentes pq eles não sabem definir o que e está estacionado e o que e está parado, fui multado por um deles por não saber qual é a diferença entre essas duas coisas, vai estudar código de trânsito assim você vai aprender a trabalhar.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('uma ferramenta importante para expor nossa reclamação e descaso com essa vergonha total que se diz transporte urbano', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('A população do Cidades dos Colibris está precisando ser atendida por uma linha de transporte público, o ônibus Integração que atendia essa região não passa mais. Alguma previsão para atendimento dessa demanda?', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('A situação dos ônibus na lagoa está caótica após a reforma. As novas paradas de ônibus tornaram as viagens muito mais demoradas. Na hora do rush fica tudo muito lento e travado para os usuários. Nas grandes cidades do mundo privilegia-se o transporte público, em João Pessoa as mudanças pioram a situação dos usuários que já pagam R$0,20 a mais por viagem do que em Recife, onde já existem ônibus com ar condicionado. Entendo as mudanças para tornar a Lagoa mais aprazível para todos, mas estas mudanças nas paradas pioraram a situação dos usuários.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Não consigo falar no numero informado. Solicito que mandem fiscalizar carros estacionado em local proibido na Rua Manoel Firmino do Nascimento, próximo a academia Top Sul, nos bancários. "Absurdo, estacionam em baixo da placa de proibido estacionar"', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Preguiça, única coisa que tenho a falar, liguei várias vezes e não atendem, ciclofaixas com carros estacionados, carros andando na contramão e eles só pensam em multar estudantes das faculdades, bora trabalhar e atender o público, muito feio receber nosso dinheiro e não trabalhar', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Poucas ações planejadas para o bem geral. Falta planejamento. ', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('agentes inexperientes ou desonestos a serviço da indústria da multa.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Melhor representação da sanha arrecadadora estatal por todos os meios, inclusive desonestos e imorais.
Valem-se da via crucis burocrática para indeferir recursos sem critério.
Valem-se da legislação para extorquir o cidadão, não para organizar o trânsito.
Uma vergonha! Ações típicas de organizações criminosas! Um trânsito sem regulamentação oficial alguma estaria mais seguro.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('segurança no transito,uma equipe sempre para ajuda no transito e o rienta motoristas', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Horrivel a mudança. 9901 e 9902. Só transitam na Josefa Taveira e não mais pela Alfredo Ferreira da Rocha. Falta de respeito com os usuários. Absurdo. Quem precisa fica sem opção. Horrível a mudanca', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('O motorista do ônibus 07106 Cristo as 17:30hs não quis abrir a porta do meio para idosos grávida e deficientes, conforme lei, tem um cartas para passageiros descer pela porta traseira contra a lei...
', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Contra a semob não mas o despreparo de alguns agentes sim carros que estão sendo multados nas vagas de carga e descarga pois as placas não identificam peso dos veículos ai alguns agentes quando ver um carro de porte pequeno como saveiro fiorino Reno querem multar e as placas também não se referem a tempo limite então agentes da SEMOB estão precisando de reciclagem', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('hoje sai de casa pra resolver umas coisas importantes, passei uma hora e meia esperando o 521 sentido centro, mas pra o terminal no vai paraíso passou 3, cheguei na integração fiquei mas 40 minutos esperando Jaguaribe 0003 e não chegou isso é muito errado para nós consumidores. terminei que não resolvi nada e pedi meu dia muito injusto. nos não estamos pedindo nada apenas nossos direitos como consumidores.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Faixa exclusiva para ônibus é uma piada, concordaria com tal faixa se ao menos os coletivos fossem de qualidade, as pessoas andam empilhadas como objetos, ônibus de péssima qualidade.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Industria da MULTA, só tem a finalidade de extorquir oficiosamente os condutores, a ordem é encher o talão para cumprir as metas (multar sem dó nem piedade). Fazendo caixinha de campanha para a próxima eleição, fora o que devem desviar...', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Se alguém puder, e tiver prestígio junto à SEMOB local, ajude os moradores da Rua Geraldo Mariz-Tambauzinho, próximo ao Espaço Cultural, mais precisamente no trecho após o restaurante Sun Sun(chinês) até a nova ponte que está sendo construída sobre a Br230. Diariamente, a rua sinalizada com "proibido estacionar" fica totalmente repleta de carros, dificultando o acesso dos moradores da referida área. A SEMOB está deixando de arrecadar uns bons trocados. Apelo a quem direito, aguardando, ansiosamente, uma reposta.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('invadindo o espaço pra fazer uma solicitação: por misericórdia! revejam a situação da linha 402 torre Tambauzinho! esse mês de julho está inviável pegar um ônibus , eu faço pós graduação dependo dessa linha e levo 1 hora e 30 min aguardando pelo ônibus, numas ruas esquisitas! por favor ajudem os moradores do bairro! está cada dia demorando mais e mais e esse mês de julho 19 piorou ainda mais !!!!', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('É lamentável esta engenharia e controle de transito de João Pessoa, basta ver o transito do altiplano ao centro, voc fica dando voltas mais voltas para voltar ao mesmo lugar, este pessoal deveria voltar a universidade para fazer uma reciclagem, afora a piora do engarrafamento Imaginem quando os prédios em face de conclusão estiverem terminados.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Quero deixar registrado que a Semob prontamente solucionou o problema no semáforo do Mangabeira Shopping. Liguei para o plantão e vieram rapido, ate achei que ia demorar por ser feriado, mas foi bem rapido! A população agradece!!', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('não serve pra nada, ninguém nessa SEMOB trabalha, o trânsito da cidade esta uma bagunça e não fazem nada', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('a gente liga para fazer uma reclamação e nunca ninguém atende', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Apesar das câmeras em Oitizeiro e em extensão a Cruz das Armas principalmente próximos aos bancos do Brasil e Bradesco motoristas atrapalham o fluxo de veículos ao estacionarem em locais proibidos', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Para que serve o telefone de reclamações da Semob se ninguém o atende?:', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Tentei ligar para fazer denúncia, mas o número não atende. Peço encarecidamente que fiscalizem o bar villa universitária (se for da responsabilidade de vcs) pois estão ocupando toda a calçada com mesas e ainda usando a calçada do prédio ao lado. O pedestre fica impossibilitado de caminhar pela calçada sendo obrigado a se arriscar no meio da rua, pois estacionam em frente ao bar e uma partr da rua fica com uma das vias interrompida. A rua é a José Firmino ferreira, (rua do portão de trás do unipê).', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('A merda ta feita!!! O transito de joao pessoa está intransitável, o povão sofrendo à espera de onibus por duas horas num ponto de onibus na lagoa. Sr prefeito,venha da uma volta no anel da lagoa', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Parabéns, SEMOB . Vocês leram direitinho o livro de como ferrar a vida dos outros.
Conseguiram ferrar a vida de quem mora em três bairros ao mesmo tempo.
Tambaú, Cabo Branco e Altiplano agora vivem juntos o caos do "novo binário".', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('O trânsito do meu Recife pode até ser caótico, mas aqui em João Pessoa é um verdadeiro show de imprudências, calçada vira estacionamento, ninguém respeita vaga de garagem, o mais comum de se ver, é motoqueiro sem capacete, sem viseira, sem retrovisor, de chinelo e transportando crianças, é crianças, já vi neguingo levando junto com sua esposa 4 crianças em uma ciquentinha em meio do trânsito da D. Pedro em horário de pico e desfilando na frente da PM e SEMOB e ninguém faz nada, parece que estamos trafengando em um sítio. Isso é uma vergonha para quem conduz, para a prefeitura de João Pessoa, Semob e a polícia militar, uma cidade tão linda mas sem respeito a vida, sem respeito ao próximo no trânsito!', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('A Fusão Das Linha 102 Esplanada Só Vai Piorar A População Da Quela Localidade , Resumindo Vocês Só Fazem Merda Até No Trânsito De João Pessoa É Por Isso Que o Diretor Da Semob Só Vive Na Bahia.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Pessoal, pra que serve tanta câmera de monitoramento se os condutores irresponsáveis de veículos não são punidos?.
São motoristas acima da velocidade permitida nas vias e motocicletas trafegando em cima das calçadas. Por pouco não fui atropelada por próximo ao Pavilha do Chá. Sem falar na imensidade de carros estacionados tomando toda a área dos pedestres.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('A faixa azul da Av. Josefa Taveira, em Mangabeira, é para a circulação de ônibus ou para expor milho?

É só o que se vê na "feirinha" em Mangabeira I', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Ja queria ter feito isso a muito tempo, em 2016 aconteceu isso e esse ano novamente... Não sei a quem recorrer, pois sou turista, necessito voltar de taxi por conta da Lei Seca e os Senhores Taxista de João Pessoa se recusam a ir para distancia curta! Do Fest Verão ou do Lovina, eles se negam a ir pra intermares, eles querem que você vá a pé... Senhores, a sua profissão é essa... Levar o passageiro aonde ele quer, pois o taximetro serve pra lhe pagar pelo seu serviço! Não foi um, não foi dois, foram três que recusaram ir para intermares... Se faz necessario, uma multa para esses senhores de mãe duvidosa, uma penalidade e uma maior fiscalização! Graças a Deus, existe tb boas pessoas na profissão e nos levaram ontem e eu fiz questão de pagar o dobro da corrida, pela disponibilidade!

Infelizmente so tive atenção de pegar uma placa de um fdp desse...

SEMOB ? você existe? ou so serve pra multar condutores de veiculo particular? Segue a placa de um dos taxis:

OGG 6384', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Semob, você é uma porcaria (em todos os sentidos)!!!!!!!!!!!!!', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('só pra registrar aqui. por favor, revejam o serviço de integração temporal. eu moro no valentina, peguei o 5100 no girador do bairro, desceu e subiu a ladeira, para o terminal de mangabeira do 301.. não demorou 10 minutos pra que eu pegasse outro onibus e ja creditou outra passagem.
hoje eu tinha apenas pouco mais de 3,50 reais no cartão (estudante). usei a primeira passagem ainda fiquei com 1,38. quando fui usar os 1,15 para outra passagem. simplesmente o leitor comeu meu credito e não liberou a roleta, e apresentou saldo insuficiente.
digo de antemão que se o mesmo voltar a acontecer e eu pularei a roleta e mostrarei a minha identificação.. agradeço a compreensão e mais ainda se alguém puder me responder.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Gostaria de dar uma sugestao para o transito por tras do CAIC-Mangabeira, as ruas sao estreitas voces poderiam coloca-las em sentido unico, tipo quem vem dos bancarios ser obrigado dobrar a esquerda no final dela, pq aquelas ruas estreitas fica dificil dar a curva um carro indo outro vindo. ', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Hoje estacionei atrás do Tambiá, depois de onde dizia que era proibido estacionar. Não atrapalhei o trânsito, nem nada.. querem dinheiro? Achei que ja pagavamos demais com tantos impostos. Agora isso vocês não vêem né?', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Alguém por favor sabe dizer se de 04:00 da madrugada qual o número do ônibus q passa na Rua 14 de Julho no bairro do Rangel.?????', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('E não encontrei onde postar um vídeo, sobre a invasão de carros e motos nas ciclovias dos bairros da capiral. E não sou ciclista, sou motorista, das q usa as faixas corretas e procuro seguir as demais regras de trânsito, mas, tbm corremos riscos de acidentes com as ultrapassagens, indevidas, pela direita e pior, nas ciclovias. Espaço de acesso só para ciclistas, alguns pedestres q precisem trafegar e uma eventual necessidade de parada de veículos para embarque ou desembarque de pessoas e/ou nos casos de emergência, por viaturas e ambulâncias, se não houver acessos nas vias normais, como tbm panes em veículos .', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Atendimento excelente,da recepção a moça da limpeza!
Acredito que nunca fui em um órgão público pra ser tao bem tratada como fui hj.
', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Quero semob agora Coelho Lisboa jaguaribe carros na rua ônibus sem lugar P parar liguei e nada', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Gostaria de saber qual providência será tomada com relação a fila de ônibus que está se formando na LAGOA? Alguma previsão de quando será resolvido esse IMENSO problema. A população está sofrendo, não basta os ônibus lotados após uma jornada de ardo trabalho, ainda teremos que passar por isso????', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Não ter um canal para denúncia e sugestões mostra que a SEMOB não se importa com a população.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Sempre uma desculpa diferente, para não fazer o serviço pelo qual pagamos para ser efetuado', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Lamentável mais uma mudanças feita pela semob em fechar o acesso a BR230 no final da Av Mato Grosso,no bairro dos estados,mais uma bagunça no trânsito de Jpa.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Gostaria de entender , como os onibus sao monitorados pela semob , e a pessoa passa 1 hora , cravado esperando esses onibus no valentina . Ou é só os do valentina que nao tem monitoramento , não é possivel , são 10 anos que eu conheço esse bairro e a situaçao permanece a mesma.
O onibus que faz jacuma shopping demorou 1 hora para passar aqui no valentina. Absurdo , temos que sair cedo de casa e mesmo assim chegar atrasados no trabalho.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Agradecemos a SEMOB por todas as contribuições feitas a nossa sociedade!
', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Olá.
Gostaria de saber a respeito dos ônibus da linha transacional (3510 e 5310)bancarios-mangabeira shopping.
Demoram bastante para passar nas paradas, em todo momento super lotados e os motorista informa que a empresa retirou ônibus da frota sem nenhum motivo. E os usuários dessa linha estão sendo prejudicados em seus compromissos e sem contar que ficar nos pontos de ônibus correndo risco de sofre algum tipo de violência.
Como se resolve essa questão dessa linha?!!!', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Recebi recentemente algumas multas aplicadas a mim, porém, elas chegaram depois do prazo para recorrer. Acontece que algumas delas não foram cometidas por mim, mas sim, por outros condutores. Enviei os dados dos condutores infratores para que os pontos da carteira fossem transferidos, porém, ao checar novamente, vi que toda a pontuação foi inserida na minha carteira.

Gostaria de saber como proceder diante dessa situação!', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Fraco, não tem como fazer denuncia de carros estacionado em lugar proibido nem outro tipo de interação, sendo assim pra que serve essa página?', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('precisa melhorar muito, e desfazer a nota que a semob deu ao site paraiba já que ,culpou os motoristas de onibus pelo engarrafamento na lagoa,o engarrafamento existe por falta de espaço.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Boa noite Semob.
Gostaríamos de saber se a linha 106 foi reduzida? Meus amigos já demora muito e desde 2013 reinvindicamos a inclusão da linha 502 Epitácio para diminuir o tempo de espera, agora com o terceiro gestor temos que resolver essa situação.
Em atenção ao loteamento Recanto Verde bairro do Geisel/Cuia nesta.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Qual a finalidade da SEMOB em tirar a Linha 102 Costa e Silva/Esplanada. Decepcionante Órgão que só serve para trazer transtorno a população!', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Veja este Video da Semob que vc não ver na tv', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Porque essa nova linha de ônibus entre valentina e mangabeira não passa próximo da UPA? Não viraram aqueles que necessitam desde atendimento.
', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Um órgão falho, conivente, de pouca atuação em questões de organização, as denúncias não correspondidas, onde a população sofre. O prefeito deveria reestruturar setor com novos dirigentes ( não indicações política) competência para que venha realizar uma administração seria e que venha beneficiar a população, com uma maior fiscalização e punir os reincidentes, casos que não são vistos pelas ruas e calçadas de João Pessoa, onde pedestres tem que dividir espaço com motos em calçadas, mesmo com denúncia não são realizadas, deixando os a mercê da sorte.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Estão precisando urgentemente organizar o transito na Duque de Caxias e na General Osório. Um monte de gente parando em placas de proibido estacionar / vaga de idosos e deficientes ocupadas tb, sem falar naqueles que resolver parar na via de transito e acham que o pisca alerta resolve td. Ajudem na fluidez do centro como um todo, esta terrível. Pq não abrem uma saída e entrada no bancários através da mata por traz da UFPB? Sei que é área de preservação, mas td pode ser resolvido da forma certa. Afinal num ja comeram um pouco da mata do buraquinho para a duplicação da BR e para a Duplicação da Pedro 2?', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Desde a semana passada a Av. Pedro II está com uma via destinada aos ônibus, causando transtornos nos horários de pique. Ao ser entrevistado, o superintendente de Mobilidade Urbana, Carlos Batinga, disse que os motoristas de carros particulares teriam de “se adaptar” às novas mudanças.
Na semana que vem as multas serão aplicadas a quem invadir a faixa destinada aos ônibus: R$ 293,47 e perda de 7 pontos na CNH. Já os ônibus que trafegarem nas vias destinadas aos carros particulares pagarão multa de R$ 195,23 e perda de 4 pontos na CNH.
Hoje, diante de tantos transtornos que a mudança está causando na vida dos motoristas de carros de passeio, Carlos Batinga disse que “O objetivo dessas mudanças no trânsito é fazer com que os motoristas de carros particulares usem o transporte público”.
Ora, todos sabem que o transporte público aqui é pra lá de caótico. Assaltos, demora na espera do mesmo, lotação que aumenta cada vez mais, falta de conforto, entre outros problemas.
Diariamente as queixas dos usuários dos tais transportes públicos se multiplicam... E o Sr. Carlos Batinga forçando a barra para que deixemos os carros em casa. Quem tiver de pegar a Av. Pedro II e precisa sair de casa às 7h da manhã... agora terá que sair às 6h.
Pergunta: O Sr. Carlos Batinga já está utilizando o transporte público???', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Bom dia estamos sem transporte para ir até o shopping mangabeira uma vez que o circular Santa Maria so vai até o meio da ladeira do José Américo. Foi retirado tb o 203 que iria até lá. Desde la já agradeço a atenção e espero uma resposta', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Por favor Semob,verificar os sinais que cruzam a Epitácio Pessoa (Rua do Concorde, Bento da Gama e Maximiano Figueiredo), passo todos os dias e ficamos em média 20mim, porque o sinal fecha com uma velocidade tão rápida que poucos carros conseguem se deslocar e com a volta as aulas nem se fala.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Que trabalho mau feito é esse que vocês fazem aqui no José Américo? Já pararam pra pensar que são os agentes que causam transtorno e engarrafamento? Atrasando trabalhadores.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Todas as vezes que vi a SEMOB em "ação" (o que é coisa rara, já que aparentemente todos eles, ao mesmo tempo, têm alguma outra coisa pra resolver), ou eles ficavam parados vendo os acidentes acontecendo, ou eles apareciam apenas vários minutos depois pra tentar remediar o problema e não conseguiam trazer solução alguma.

Estou pra ver o dia em que algum agente desse órgão vai realmente cumprir a função que lhe é devida.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Moro no bairro de Paratibe em João Pessoa, gostaria de denunciar a péssima qualidade do transporte ofertado pela empresa "São Jorge" nas linhas 118 e 1008, que são as únicas opções próximas a minha casa.

Por muitas vezes vemos motoristas queimando paradas e "pegando atalhos" deixando de pegar passageiros que precisam esperar muitas vezes mais de 90min por um outro ônibus. Sem contar as portas quebradas e poltronas soltas com as bases enferrujadas, fazendo com que nós passageiros tenhamos que nos arriscar para manter nosso compromissos (este caso aconteceu hoje na linha 1008 e carro 0211). Já tive que viajar em ônibus com goteiras e janelas quebradas e dividir espaço com um rato morto dentro do "transporte", o que mais é preciso acontecer?

Gostaria de saber como proceder para que providências possam ser tomadas no sentido de fiscalizar estas linhas no intuito de melhorar o serviço pelo qual pagamos, e pagamos caro.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Meu registro é uma reclamação sobre os horários confusos e sem fiscalização dos ônibus ( 201/202/204 ) que saem da integração a noite, especialmente nos domingos e feriados. Eu trabalho a noite, e costumeiramente embarco em algum desses ônibus, que saem às 23:30 da integração, exceto o 204, que geralmente passa mais cedo. Mas 201 e 202 sempre é o mesmo horário. Acontece que ontem ( 07/08 ) cheguei na integração às 23:10, esperei até 23:46, e como não passou nenhum deles, fui perguntar na cabine da SEMOB se o horário havia sido alterado, e o atendente me respondeu que : às vezes muda. OI? Mas quando muda, nós usuários não devemos ser informados? Então é normal que um cidadão perca 1:10 do seu precioso tempo, porque o ônibus passou antes da hora e quem deveria fiscalizar não viu, ou mudou o horário e quem deveria saber não sabe informar? Um pouco mais de organização, profissionalismo e respeito, é o mínimo que devem ter para com os usuários!', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Depois de alguns anos morando fora de João Pessoa, retorno e volto a morar no jardim 13 de Maio. E percebo que o descaso com os moradores do bairro ainda continua, não falo da falta de segurança e nem da coleta de lixo e sim em relação ao transporte coletivo. É um absurdo a falta de respeito dessa empresa que tem o monopólio dessa linha com as pessoas que dependem dela. Eu vim morar aqui porque meus filhos passaram a estudar em João Pessoa, um em Jaguaribe, no IFPB e o outro na UFPB. Achei que sair de Cabedelo, seria melhor para os dois, mesmo tendo que eu ir todos os dias para trabalhar lá. Que ingenuidade a minha, A falta de um critérios nesse horários fazem com que eles sempre cheguem atrasados, ou que para poderem chegar na hora tenham que sair de casa no mínimo duas horas mais cedo. Gente, na última sexta, à noite, estava no ponto de ônibus e vi passar no seis coletivos Mandacarus, dois bairros dos Ipês e um Padre Zé. Este último lotado, por sinal. Quando veio o segundo, onde pude entrar, perguntei quantos ônibus estavam fazendo esse itinerário e o motorista respondeu que tinham quatro e que a demora se deu por conta das manifestações. Será que só não deixaram passa o Padre Zé? Minha pergunta é: O que já foi feito em relação a isso? E o que pode ser feito para que o povo do jardim 13 de maio seja tratado com o respeito que merece? Não se trata de um favor e sim de um direito nosso. O SEMOB, enquanto orgão regulador do transporte e trânsito de Joâo Pessoa, podem nos oferecer uma solução para esse antigo problemas que dificulta a mobilidade dos residentes deste bairro?', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Bom dia deixo meu manifesto sobre as linhas de ônibus existente em nossa capital educação no transito no tocante destes condutores de ônibus que dependem de nós usuários de coletivo. Fico estressado com o tratamento que fornecidos por este motoristas que não tem nenhum respeito por aqueles que depende do transporte coletivo para chegar no seu destino que na maioria seria destino de trabalho, diversos problemas como queimada de parada a forma abusiva que somos tratados por esta categoria, acho que todos que atuam nesta atividade tem plena consciência do seu trabalho: vou citar alguns abuso que passo diariamente.
I - Há uma fila de ônibus na parada o seu é o ultimo ônibus depois de passar todos você pede para o motorista faz questão de para 50 metros depois só para ver você caminhar, considero isto uma maldade.
II - Você pede parada mais o ônibus não para este condutores de ônibus não nenhum respeito pelo os usuários, isto é desumano .

Para finalizar digo e afirmo que não órgãos publico competente para resolver este descaso com os usuários de coletivo urbano fica parecendo que cada motorista é dono da empresa e age de qualquer maneira responsabilizo também aos empresários que não tem uma fiscalização eficiente para acompanhar este descaso com a população que utiliza sistema publico de ônibus coletivo. Publico privado pois todos os motoristas se tornaram proprietários dos ônibus pertencentes as empresas de ônibus de nossa capital.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Gostaria de registrar uma ocorrência de abuso de poder e possível dano material oriundo de um dos agentes da SEMOB.
Foi hoje, 24/04/2017, por volta das 14h50, no trevo das Mangabeiras, sentido Bancários/Mangabeira. A ação correspondia a um isolamento de área onde houve um acidente. Estavam no local uma viatura do SAMU, uma pickup adesivadas e duas motos adesivadas. Havia um agente no lado direito e dois do lado esquerdo da via. O trânsito estava lento no local. Quando passei pela faixa de pedestres, onde estava um agente do lado direito, este não fez sinal algum indicando se eu deveria parar, então passei lentamente, pois havia um veículo à minha frente. Então, o agente que estava à direita bateu no meu veículo, com uma das mãos e com bastante força e começou a gritar comigo. Eu baixei o vidro e perguntei o que houve e ele respondeu, ainda gritando "Você não viu que tem uma faixa de pedestre aqui? É por isso que se envolve em acidente e mata pessoas!". Uma informação básica, para início de conversa: NUNCA me envolvi em acidente algum! Depois ele passou para o outro lado do meu veículo e eu baixei o vidro e questionei-o acerca da necessidade de tal ato violento. Ele prontamente respondeu, gritando "Precisava sim!" e continuou esbravejando. Eu disse que ele era "covarde" por estar gritando com uma mulher e ele me ameaçou com uma "canetada". Então eu disse: dê a canetada, então, só não seja covarde! E ele me mandou ir embora. Segui em direção a mangabeira, e, mais adiante, resolvi voltar para pegar os dados tais como placas e nomes dos agentes. Porém, ao chegar no local, eles já não estavam mais.
Pela data e horário talvez seja possível identificar o agente que me causou tal transtorno. Acredito que a SEMOB seja íntegra no que se refere a coibir quaisquer ações de abuso de poder. Nenhum cidadão deve passar pelo o que eu passei!
Aguardo retorno.
Obrigada!', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Vários pedidos feitos e nunca ouvidos cruzamento da Visconde itaparica com índio piragibe vários acidentes inclusive com vítimas fatais grande congestionamento tudo por uma falta de um simples semáforo ABSURDO VAI MORRER MAIS QUANTOS REVOLTANTE O ABANDONO VEJAM VIDEO NOS COMENTÁRIOS', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('A SEMOB precisa marcar presença no Bairro dos Bancários, na Rua João Rodrigues Alves, no segmento entre o Frigorífico Bela Vista e o Bemais, onde condutores param de forma atabalhoada, ligam o pisca alerta e passam todo o dia provocando a desordem no trânsito. Passar também, na baia do ponto de ônibus do Shopping Sul, onde os veículos pequenos e Carros de Transporte de valores param no interior da baía e impedem a parada dos ônibus, para embarque e desembarque de passageiros. Passar ainda, na Rua João Galiza, no Bairro Jardim São Paulo e orientar os caminhões que descarregam no depósito do Bemais.

.

.

A SEMOB precisa marcar presença na rotatória próxima ao Campus I da UFPB. Na que insere os veículos oriundos do Castelo Branco no Corredor Pedro II, em direção aos Bancários ou ao centro da cidade, orienta-los a aguardar o momento de entrar na via, evitando o avanço sobre os veículos oriundos dos Bancários. Orientar os veículos vindos dos Bancários, na entrada da rotatória para descer para o IBAMA que, quando visualizarem os veículos vindos do IBAMA em direção ao Castelo Branco que, os dos Bancários NÃO DIMINUAM a MARCHA e PASSEM e SIM, RETENHAM-SE, para proporcionar a entrada desses veículos para o Castelo Branco, essa retenção proporcionaria também, o tempo necessário para a inserção dos condutores do Castelo Branco na Pedro II e evitaria os AVANÇOS. Deve-se levar em consideração que a retenção dos condutores oriundos do Castelo Branco e os avanços são consequentes do volume MAIOR do fluxo dos veículos que vem dos Bancários em direção ao IBAMA.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Bom dia resido na Av São Gonçalo nº 89. quero pedir por gentileza que seja colocado uma placa na esquina da João Mauricio Administradora ELLO, os funcionarios estão impossibilitando a passagem de pessoas que precisam usar a calçada dessa administradora, a mesma faz da calçada estacionamento de motos, podendo causar acidente em quem usa essa calçada para ir a praia ou caminhar, pelo que sei a calçada é de via de pedestre, espero que tomem as devidas providencias. AGRADEÇO MUITO SE FOR COLOCADO UMA PLA RECOMENDANDO QUE SERÁ SUJEITO A REBOQUE CSO ESTACIONE NA CALÇADA DA ADMINISTRADORA ELLO: Att: Maria da Penha Souza Lins.
', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('RELATO DE UMA PESSOENSE DEPENDENTE DO TRANSPORTE PÚBLICO:

Você acha essa cena absurda?
Pois é, isso é o meu dia-a-dia. Saiu de casa ao nascer do sol, 05:00am estou saindo de casa para o meu trabalho, como toda cidadã, pego o ônibus, chego ao meu local de trabalho um ambiente alegre, onde dou meu sangue com o maior prazer por amar o que faço, começo minha jornada até às 17:00pm, e daí começa o pesadelo: ESPERAR O ÔNIBUS DE VOLTA PRA CASA.

Após esperar o ônibus do bairro onde moro por pouco mais de 40min, tem dias que a espera chega à 60min, subo no mesmo que já está com todas suas cadeiras ocupadas, vou para a traseira do mesmo, pensando que eu que embora estive em pé não passaria tanto sufoco, pois bem, engano meu.
Todos os dias é uma triste realidade enfrentada por mim com bastante revolta e pesar de ver tantos trabalhadores passando pela mesma humilhação que eu, vamos um sentindo a respiração do outro, não há espaço para mexer os pés, gente em cima do motor ao lado do motorista, nas escadarias, em pé por mais de 40min até chegar ao destino, essa sentada sou eu, num momento de cansaço extremo, sentei nas escadarias porquê minhas pernas já não aguentavam mais está encolhida entre tantas pessoas. É um absurdo o que passamos todos os dias, somos PARAIBANOS, moramos em João Pessoa e não recebemos o mínimo de respeito dessas empresas corruptas, representantes políticos da nossa cidade que só pensam em encher suas contas bancárias e não pensam em como fazer para oferecer um transporte digno, de vergonha a essa população trabalhadora e dependente da porcaria desses ônibus. O funcionamento do transporte público em João Pessoa está cada dia mais precário, ônibus quebrados, sujos, profissionais desqualificados, poucos ônibus pra atender uma demanda absurdamente maior, O VALOR DA PASSAGEM É UM ABUSO, UM ASSALTO À MÃO ARMADA, e os empresários, claro que com respaldo da prefeitura de João Pessoa anuncia um aumento na pasaagem, e agora eles nos roubam todos os dias 3,00, vamos pagar 3,00 reais por um serviço lixo, defasado, humilhante, onde se ver no semblante das pessoas o suor, o cansaço demasiado de um povo que sofre, por não ter outra opção. #revolta', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES(', VEJA AS IMAGENS DO CARRO DE COMBUSTÍVEIS PERNOITANDO N RUA. JOÃO BEIROZ SILVA AO LADO DO COLÉGIO JOÃO R. BORGES EM MANGABEIRA. JOÃO PESSOA.....ATENÇÃO PESSOAL NOS AJUDEM A DIVULGAR ESTE LINK NO SEU FACEBOOK, MORADORES EM DESESPERO, TÁ PERNOITANDO TDS OS DIAS, O SUJEITO É AGRESSIVO E IMPETULANTE . O CARRO É DE GRANDE PORTE. É O DONO DO POSTO BSB. A SITUAÇÃO FICOU MT CRITICA O TRAFEGO NO LOCAL CAUSANDO SÉRIOS TRANSTORNO NA ÁREA DIFICULTANDO A PASSAGEM DOS CARROS. desde de sexta-feira q tá no local', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('a semob e um orgao que nao esta resolvendo em nada os problemas de mobilidade e pessima realmente existe mas nao fuciona', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Acho a Semob uma grande prestadora de relevantes serviços prestados a cidade de João Pessoa - Paraíba.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Semob por favor coloque ônibus no terminal do 303 mangabeira por dentro com acesso a escola ana Cristina Machado e ao Chopin mangabeira Detran e etc. Estamos precisando urgentemente tenho filhos pequenos e está muito difícil descer nos bancários e seguir a pé com as crianças até a escola, principalmente nos dias de chuvas. Obrigado', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Como moro no José Américo gostaria que com novo trevo de Mangabeira alterasse uma das linhas(já existe )q nos conduzisse até Bancários sem precisar integrar a estes bairros são tão próximo .Podem achar q as linhas 2515 q passa no JA.dá certo,mas o tempo é gd pque tem q ir no centro p passar no Bancários.O mesmo acontece c as linhas 5206, 5210 e 5209 vem de mangabeira p ir p JA precisa a ir no centro p chegar no JA ou integrar na UFPB.Acredito que com as alças do viaduto de Mangabeira façam uma alteraçao nessas linhas ou melhor no intinerário. Obg. fica minha sugestão.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Atenção Semob, a BR 230 sentido Cabedelo-Jp está um caos! Trânsito lentíssimo. Há mais de 40 min estamos praticamente parados em apenas um trecho!', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Achei lamentável a total ou quase total ausência do SEMOB / João Pessoa no que diz respeito ao controle do trânsito deste domingo (19/ 07/ /2015) nas áreas da nossa Capital onde houve provas para o Concurso para o Ministério Público/PB. Houve congestionamento, carros circulando na contra- mão, outros ostensivamente estacionados em locais proibidos, até na entrada de garagens de edifícios, como aconteceu no meu , tudo isso impunemente ! Nao houve sequer a preocupação de desativar as ciclovias que costumam criar aos domingos na avenida Epitácio Pessoa. Pessoas de outros estados revoltadas com esse caos em Joao Pessoa , ficando assim uma péssima impressão sobre a nossa cidade ale além de ter dificultado e muito o acesso aos locais de provas! Nós pessoenses ficamos com um misto de vergonha e revolta com tamanho descaso !
', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('A linha 202 do bairro do Geisel, é servida por 4 ônibus em seu percurso até o centro da cidade .Hoje toda populaçâo do Geisel sofre com ônibus cheios, demora nas paradas de ônibus e quando vem lotados gerando vários contrangimento aos passageiros .
Secrétario da SEMOB olhe para o geise.
Junio Som
Foto de Junio Som Batista.
', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('E UMA EMPRESA SERIA E UM BOM DESEMPENHOS NAS RUAS DE JOÃO PESSOA', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Depois de idas e vindas por 15 dias em um hospital da cidade, notei uma total ausência de placas de proibido buzinar em frente as nossas casa de saúde. Quanto custa uma placa destas? R$200, R$300, não importa ; o que importa e muito, são os incômodos para quem está enfermo, internado nestas instituições, com os absurdos que observei provocados por motoristas mau-educados e desavisados que "tacam" a mão na buzina sem se importar em que área estão . Seria bom que a SEMOB olhasse também para esta situação e ao menos colocasse placas de PROIBIDO BUZINAR previsto no CNT ou se preferir "colocasse " um amarelinho diante destas instituições que com certeza iria ENGORDAR O COFRINHO com os constantes flagrantes do dia a dia. Em tempo: BUZINAR EM FRENTE A HOSPITAL É INFRAÇÃO LEVE, RENDE 03 PONTOS NA CARTEIRA E CUSTA R$ 53,20.
OS PACIENTES DESDE JÁ, AGRADECEM!', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Tive o pra ser de conhecer esta linda capital, com suas obras futuristas e arrojadas. Parabéns Porto Velho.', 1);
INSERT INTO comentario (comentario, usuario_id) VALUES('Elogios, Eu Vicente Bernardo, sou usuários dos transportes publico por opção, sempre utilizo em meus deslocamentos as linhas 301, 5206, 5600, 2514, 3200, 2300, e estas linhas são realmente digina de elogios, sendo que sempre de tres a quatro vezes por semana utilizo as linhas 5100 e 1500, estas realmente teem deixado muito a desejar.

Reclamação: sempre pego ônibus 5100 em Cruz das Armas, entre as 19:30hs e 20:45hs, sempre enfrentando todos os problemas de sempre, como atraso, troca de ônibus nos terminais, longo período de espera entre 10 a 20 durante estas trocas de veículos, longos períodos de esperas. Mas ontem tive o maior desprazer, ao pegar o onibus 5100 de prefixo 07110, as 21:30hs, sendo que ao chegar no terminal do Geisel não tendo nenhum outro veiculo para nos conduzir ate ate mangabeira , o motorista informou que iria recolher , e obrigou os passageiros a descer sem ter nenhum onibus para transferência dos passageiros para o outro o ônibus, o fiscal já teria saido de seu posto.

Sugestão: sugiro que todos os onibus circular da linha 5100, recolha na CHEAP em mangabeira, entendo que não geraria custo para a empresa, com isso evitaria de muitos passageiros fiquem nas paradas a noite, o motorista e cobradores gritando só vai ate o GEISEL, a empresa deveria colocar um fiscal desconhecido dos motoristas e cobradores para verificar quantos passageiros ficam pelo caminho, nas paradas ao ser informados que o ônibus só vai ate o Geisel, onde muitos moram em mangabeira, ou de outros bairros, mas sendo que em Mangabeira você tewm outras opção. Diante deste reclamo e sugestão gostaria de obter uma resposta.', 1);
