CREATE TABLE public.comentario(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    comentario varchar(255) NULL,
    usuario_id int4 NULL,
    CONSTRAINT comentario_pkey PRIMARY KEY (id),
    CONSTRAINT fkiso72ajmkk36lw7dqasdfasdf FOREIGN KEY (usuario_id) REFERENCES usuario
);